[properties]
id = "объект_3"
type = "Персональный компьютер"

[properties.name]
default = "Настольный ПК"
ru = "Настольный ПК"
en = "Desktop PC"

[[parameters]]
id = "процессор"
type = "string"
required = true
default_value = "Intel Core i5"
possible_values = ["Intel Core i3", "Intel Core i5", "Intel Core i7", "AMD Ryzen 5", "AMD Ryzen 7"]
value = "AMD Ryzen 7"

[[parameters]]
id = "объём оперативной памяти"
type = "integer"
required = true
default_value = 8
possible_values = [4, 8, 16, 32, 64]
value = 16

[[parameters]]
id = "объём жёсткого диска"
type = "integer"
required = true
default_value = 512
possible_values = [256, 512, 1024, 2048]
value = 1024

[[parameters]]
id = "графический процессор"
type = "string"
required = false
default_value = "Встроенный"
possible_values = ["Встроенный", "NVIDIA GeForce", "AMD Radeon"]
value = "NVIDIA GeForce"
